### ISSUE TITLE
Language choosing on first run

### ISSUE THREAD

**Issue by GoRaN9O** [AlfaazPlus/QuranApp#123]
### Describe your suggested feature

السَّلَاْمُ عَلَیْکُم وَ رَحْمَةُ اللّٰهِ وَ بَرَکَاْتُه

Could you please add new option like ( Select Theme, Select Reciter ) when user install the QuranApp for the first time to select the app language manually from available languages.

![Screenshot_20230322_205430_QuranApp](https://user-images.githubusercontent.com/3160786/226997021-0caaf1b1-4c71-44a3-a036-8a538821160c.png)

GOD Bless You For Making This Great and Amazing Quran App Baraka Allah Fik.

### Other details

This option is very good for those who there device language is English but wants to use the app in it's native language.

Best regards. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
Added to the [milestone](https://github.com/AlfaazPlus/QuranApp/milestone/2).
