### ISSUE TITLE
Fix verse number

### ISSUE THREAD

**Issue by xmha97** [AlfaazPlus/QuranApp#133]
### Steps to reproduce

Hello, Ramadan Mubarak

Please fix verse number:

![Screenshot_2023-03-25-02-03-32-904_com quranapp android](https://user-images.githubusercontent.com/23485114/227655642-d66d6de9-b9a3-4b0a-b2fe-b2cbc6bea966.jpg)

### Expected behavior

9, 10, 11, 12, 13

### Actual behavior

9, 1, 11, 21, 31

### QuranApp version

2023.03.21.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.

**Comment by faisalcodes** [comment]
Working on it.

**Comment by xmha97** [comment]
> Working on it.

Thanks 🙏

**Comment by faisalcodes** [comment]
Can you check the [debug build](https://github.com/AlfaazPlus/QuranApp/suites/11807915342/artifacts/616371454) if the issue is resolved?

**Comment by xmha97** [comment]
I think this problem is solved.
thank you.
