### ISSUE TITLE
I hope to add Interpretation of the Quran

### ISSUE THREAD

**Issue by amrelhossieny** [AlfaazPlus/QuranApp#143]
### Describe your suggested feature

If you can add interpretation in each verse and thanks for your hard work brother and Ramadan Mubarak 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
I had added tafsir for each verse in the past, but due to some bugs I had to remove it. InshaAllah I will try to add it again.

**Comment by amrelhossieny** [comment]
Thanks brother for your work, God bless you
