### ISSUE TITLE
App Crashes

### ISSUE THREAD

**Issue by rai61354** [AlfaazPlus/QuranApp#15]
### Steps to reproduce

Aslam o alaikum!

I want to contribute in Quran translations. But app crashed when I clone the project on my Android Studio. I setup the firebase and enable all required services from firebase like Realtime Database, Cloud Storage, Authentication and Cloud Firestore but when I run the app I got this error in error log.

 Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.acun.quranicplus.debug. Make sure to call FirebaseApp.initializeApp(Context) first.

Can you please tell me how to fix it?
JazakAllah :-)

### Expected behavior

.

### Actual behavior

.

### QuranApp version

.

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
We are gradually moving away from the firebase. I will tell you how to fix this in a moment.

**Comment by faisalcodes** [comment]
I don't see any forks in your GitHub profile. Kindly fork this project and then clone your repository.

**Comment by rai61354** [comment]
> I don't see any forks in your GitHub profile. Kindly fork this project and then clone your repository.

1: I've frok the project.
2: I've configured the package name and enable Realtime Database, Cloud Storage, Authentication and Cloud Firestore from firebase
3: I placed the google-services.json inside the app folder

but now I'm getting the error No matching client found for package name 'com.raiadnan.quranreader.debug'

Screenshot: https://i.ibb.co/D5BXGRg/Error.png

**Comment by rai61354** [comment]
When I removed id 'com.google.gms.google-services' from gradle then No matching client found for package name issue resolved but getting another error
 Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.raiadnan.quranreader.debug. Make sure to call FirebaseApp.initializeApp(Context) first.

Screenshot 2: https://i.ibb.co/zRyyQPh/Error.png

but the question is here is my packagename com.raiadnan.quranreader but android studio automatically generated this packagename com.raiadnan.quranreader.debug

why android studio generated .debug in the package name?

**Comment by faisalcodes** [comment]
Kindly do not change the package name. I am working on removing the Firebase from the app. So you can wait until I complete that or try to figure out your problem.

**Comment by faisalcodes** [comment]
This project is setup to create two variants of the app one for debug and another for release. So you need to add the package name with debug suffix in your Firebase for it to work. 

Try to update your branch as I have made new changes.

**Comment by rai61354** [comment]
> Kindly do not change the package name. I am working on removing the Firebase from the app. So you can wait until I complete

1: All previous errors resolved now getting another error
    java.lang.IllegalArgumentException: The supplied bucketname does not match the storage bucket of the current instance.

App Crashed when open any surah in the app. Please check the attached screenshot for the reference.

Screenshot 3: https://i.ibb.co/G350cQk/Error.png

**Comment by faisalcodes** [comment]
In the `ApiConfig.kt` change `gs://the-quranapp.appspot.com` with your own. You can find your bucket name in `google-services.json`.

**Comment by rai61354** [comment]
> @rai61354 In the `ApiConfig.kt` change `gs://the-quranapp.appspot.com` with your own. You can find your bucket name in `google-services.json`.

Alhamdulillah all errors resolved and App running without crash. But when I try to play any verse I got error
Something happened wrong while loading the verse.

When I go to settings to select the reciter also got error
Could not load recitations from the server. Please try again later.

Screenshot: https://i.ibb.co/xYB4d96/Error2.jpg

**Comment by faisalcodes** [comment]
@rai61354 Yes, those things will not work in debug mode because these resources are uploaded on firebase which your firebase projects doesn't have. If you want you can contribute to other feature or wait few days until I move away from firebase.

**Comment by rai61354** [comment]
Ye

> @rai61354 Yes, those things will not work in debug mode because these resources are uploaded on firebase which your firebase projects doesn't have. If you want you can contribute to other feature or wait few days until I move away from firebase.

Yes I will start work on translations. I've some verified translations. Also can you please share filebase json files to load reciters and verse?

**Comment by faisalcodes** [comment]
Wait until tommorow, You will find all the resources here.

**Comment by rai61354** [comment]
JazakAllah :-)

**Comment by rai61354** [comment]
> Wait until tommorow, You will find all the resources here.

Aslam o alaikum bro from where I find all the resources?

**Comment by faisalcodes** [comment]
I am still working on it. If you'd like to contribute a translation you can read [this](https://github.com/AlfaazPlus/QuranApp/blob/master/CONTRIBUTING.md#quran-translations).

**Comment by rai61354** [comment]
> I am still working on it. If you'd like to contribute a translation you can read [this](https://github.com/AlfaazPlus/QuranApp/blob/master/CONTRIBUTING.md#quran-translations).

Yes I'm working to implement mufti taqi usmani urdu translation's in json file according to your format but yesterday you said you will post resources here. That's why I'm saying app working fine but other features not working from my side due to resources , can you please share the resources?

**Comment by faisalcodes** [comment]
It may take more time to migrate away from firebase. I hope it to complete by today InshaAllah. You can try the live app for other features to work. [Link](https://play.google.com/store/apps/details?id=com.quranapp.android)

**Comment by faisalcodes** [comment]
@rai61354 You may find all the resources in [inventory](https://github.com/faisalcodes/QuranApp/tree/master/inventory). Be sure to update your branch and share this project with others if you can. Jazakallah

**Comment by rai61354** [comment]
> @rai61354 You may find all the resources in [inventory](https://github.com/faisalcodes/QuranApp/tree/master/inventory). Be sure to update your branch and share this project with others if you can. Jazakallah

1: Alhamdulillah I've successfully translated first 19 Surah. Today I tested your complete app and one thing I noticed in debug mode your app working fine but when you release the signed apk and install in your device Reciter not loaded and showing "No recitations available" I didn't tested full app yet but I noticed an error in the reciter section.

2: also tell me do you know any way to copy translations from sql to json? because I've verified mufti taqi usmani urdu translation that is available in Islam360 and I'm trying to coping ayah by ayah in json file which is taking so much time so there is any way to copy translation from sql to json in easy way?

**Comment by faisalcodes** [comment]
I will look into your first point. Yes, we can copy translations from sql to json.

**Comment by faisalcodes** [comment]
Assalamualaikum brother. What's the progress of your translation?

**Comment by rai61354** [comment]
Wa alaikum Aslam brother. first 22 surah completed. 
1: can you please guide me a quick way to copy the translation from sql and paste in json?
2: I've a question I'm learning firebase so can I configure your very first version on firebase and upload inventory for the learning purposes if you allow?
3: Did you check the issue why reciters not available on release version? because everything's fine in debug.
