### ISSUE TITLE
Linking and Tagging by user, show topics of verses

### ISSUE THREAD

**Issue by a-xq** [AlfaazPlus/QuranApp#16]
### Describe your suggested feature

Assalamu alaykum
the app is great, however it would be nice to have these features as well:

- Linking verses by user with ability to export linked verses later for backup
- Tagging verses by user with ability to export tagged verses and tags later for backup
- Show topics of each verse, currently you cannot see under which topics a specific verse is listed

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
What do you mean by `linking and tagging verses by user`? We don't need to show topics on each verse. Topics are listed on a different page and verses related to a topic is shown on a specific page.
