### ISSUE TITLE
Improve status bar icon

### ISSUE THREAD

**Issue by xmha97** [AlfaazPlus/QuranApp#178]
### Describe your suggested feature

Please improve status bar icon.

![IMG_20230402_232459_125](https://user-images.githubusercontent.com/23485114/229375877-65bd5203-a227-49b9-8515-9572670d4536.jpg)

![IMG_20230402_232458_125](https://user-images.githubusercontent.com/23485114/229375880-f384fdf9-2cf3-4bc3-8edb-cabfd3f929e7.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
I am planning to improve the recitation player as a whole which will improve the notification and icon. Today a new release has been published and targeting this one for next release InshaAllah.

**Comment by xmha97** [comment]
> I am planning to improve the recitation player as a whole which will improve the notification and icon. Today a new release has been published and targeting this one for next release InshaAllah.

Thanks.
Please also use the Android media notification. (Like Telegram messenger)

![Screenshot_2023-04-03-01-56-12-379_org.telegram.messenger.web.jpg](https://user-images.githubusercontent.com/23485114/229382471-617074d3-e061-4506-bb48-33099dff7aa5.jpg)

**Comment by faisalcodes** [comment]
Yes that's a purpose of improvement.

**Comment by xmha97** [comment]
Thanks 🙏
