### ISSUE TITLE
Move tafsir & share button to the main Quran page 

### ISSUE THREAD

**Issue by GoRaN909** [AlfaazPlus/QuranApp#180]
### Describe your suggested feature

Salamu Alikum Brother

Could you please move the Tafsir & Share an Ayah to the main Quran page next to the Bookmark and Playing buttons.

![Screenshot_20230404_072800_QuranApp Debug](https://user-images.githubusercontent.com/3160786/229687569-b9d227fc-f2ab-4e4d-986f-27198a9d4ff8.png)

### Other details

Also replacing the play button by the select reciters is will be more comfortable because play button is already available in two other places.

![Screenshot_20230404_073526_QuranApp_Debug 1](https://user-images.githubusercontent.com/3160786/229688155-5176698c-d9dd-475f-bdda-91665f90f439.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
Only tafsir button should be moved, share button is not frequently used.

**Comment by faisalcodes** [comment]
All the buttons on the verse should also be available in VerseOptionsDialog. Reciter selector button is already there for convenience.

![IMG_20230404_112743.jpg](https://user-images.githubusercontent.com/62804272/229700737-fccc0d14-a8a6-41a1-a0e1-5be16bc5e970.jpg)
