### ISSUE TITLE
Symobols misplaced in Font IndoPak

### ISSUE THREAD

**Issue by Luciogi** [AlfaazPlus/QuranApp#183]
### Describe the issue

Symbols occurring among verses are misplaced 

### Screenshot

![Screenshot_20230404-142953_QuranApp](https://user-images.githubusercontent.com/84625092/229752578-526870a7-ac28-4ca0-9cd2-cbe7b658ee57.png)

![Screenshot_20230404-143308_QuranApp](https://user-images.githubusercontent.com/84625092/229752609-0a7941b3-fd5f-4c27-aeb0-40deb7432275.png)

### Chapter and verse numbers

Chapter No: 1 and verse no: 7 , Chapter No: 2 and verse no: 2 

### QuranApp version

2023.04.02.1

**Comment by faisalcodes** [comment]
The problem is with the font. I cannot hope any solution until the problem is fixed at original author's side.

**Comment by Luciogi** [comment]
@faisalcodes  Please share Original source link for script

**Comment by faisalcodes** [comment]
@Luciogi I have taken the font from quran.com. It works better on the website, but it seems to be having incompatibility issue with Android.

**Comment by Luciogi** [comment]
https://github.com/marwan/indopak-quran-text 
Can you use this project?

**Comment by faisalcodes** [comment]
It is mentioned on the repo to not use it. But let me try it.

**Comment by faisalcodes** [comment]
> Quran.com 's android app using these resources

I actually used the font from this repository but see no change.

**Comment by Luciogi** [comment]
IndoPak is also know as [Hafs Nastaleeq Font](https://fonts.qurancomplex.gov.sa/wp02/en/hafs-nastaleek/) 
Try this font

**Comment by faisalcodes** [comment]
I have found a fix for the issue. I will update it once I finish the work on recitations, InshaAllah.

**Comment by faisalcodes** [comment]
I have manually improved the script as much as I could. Please report it to me if you find other misplaced characters. You may join our [discord server](https://discord.com/invite/vtutnwzxRb) for further communication.
