### ISSUE TITLE
Switching script causes reader to scroll to the top

### ISSUE THREAD

**Issue by Luciogi** [AlfaazPlus/QuranApp#185]
### Steps to reproduce

1. Open Chapter longer than 1 page. e.g Chapter No: 2
2. Scroll manually to page 2 or 3.
3. Change script from Settings

### Expected behavior

It should remember page position

### Actual behavior

Directed to 1st page of Chapter

### QuranApp version

2023.04.02.1

### Android version

Android 13

### Other details

https://user-images.githubusercontent.com/84625092/229760469-04bb1de9-241b-42bf-8a81-3810eb309999.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
It remembers the verse number when reading in `translation layout mode`. It should also remember in `page layout mode`. Will work on it 👍.

**Comment by Luciogi** [comment]
@faisalcodes this bug still exist 
Tested in Debug version

**Comment by faisalcodes** [comment]
Have you updated your branch?

**Comment by Luciogi** [comment]
Yes, it is uptodate

**Comment by faisalcodes** [comment]
Kindly send a recording.

**Comment by faisalcodes** [comment]
@Luciogi Kindly join our [discord server](https://discord.com/invite/vtutnwzxRb) for detailed discussion.

**Comment by Luciogi** [comment]
> @Luciogi Kindly join our [discord server](https://discord.com/invite/vtutnwzxRb) for detailed discussion.

I was banned from discord, I wont want to use it anymore.
I would Like to Invite to [Matrix chat](https://element.io/)

**Comment by faisalcodes** [comment]
We have [matrix](https://matrix.to/#/#quranapp:matrix.org) as well.
