### ISSUE TITLE
al jalalayn tafsir in english 

### ISSUE THREAD

**Issue by printyfi** [AlfaazPlus/QuranApp#213]
### Describe your suggested feature

any chance this could be added https://raw.githubusercontent.com/galacticwarrior9/IslamBot/master/tafsir/tafsir_jalalayn.txt

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
Let me check it.
