### ISSUE TITLE
Contact with you

### ISSUE THREAD

**Issue by ahmedaa6122** [AlfaazPlus/QuranApp#215]
### What is your question?

I need contact with you please WhatsApp or telegram. Please. 

### Acknowledgements

- [X] I have searched for existing issues and have **not** found an answer to my question.
- [X] I have included all necessary details in my question.
- [X] I understand that the maintainers or contributors may not be able to immediately respond to my question.

**Comment by faisalcodes** [comment]
You can contact me on discord at [this link](http://discordapp.com/users/955774245152100403).
