### ISSUE TITLE
Media buttons support and auto-pause on headphones disconnect

### ISSUE THREAD

**Issue by talal** [AlfaazPlus/QuranApp#221]
### Describe your suggested feature

As-salamu alaykum,

First of all thank you for this great app, جَزَاكَ ٱللَّٰهُ خَيْرًا

I used to use another app for listening to Quran and two thing that I miss from it, and these are features that I believe will be useful to others too, are media buttons support and auto-pause when playback device disconnects.

Android apps can utilize the media buttons on headphones, and other devices, to pause/resume and skip/rewind the media. Android also has support for pausing media if the external playback device such as headphones are disconnected/unplugged.

This auto-pause feature is especially useful for wireless earbuds so that when you take your earbuds out from your ear and put it in its charging case, the earbuds are disconnected (bluetooth disconnection) from your phone and that leads to the audio getting automatically paused.

This lack of auto-pause can also be inconvenient sometimes, e.g. if you're in a crowded place and listening on your earbuds then putting them back in their case will switch the audio to the loudspeaker and you have to take out your phone and manually pause it.

I believe that media button support and auto-pause will be a great addition to this app as many people use wireless headphones and they would greatly benefit from this.

Here is a link to Android developer docs for your reference: https://developer.android.com/guide/topics/media-apps/mediabuttons

Regards,
Talal

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
Walaikum Assalam, Thank you for the detailed explanation. The app has been using old style [MediaPlayer](https://developer.android.com/guide/topics/media/mediaplayer) for playing audios. I wasted over 5 days implementing "recitation with translation" feature using the same tool. When it was getting out of hand to keep all the advanced features in place, I thought to migrate to Google's ExoPlayer. I started working on implementing the feature along with others which is about to be finished and you can track the progress in [this PR](https://github.com/AlfaazPlus/QuranApp/pull/211).

The features you described are must-haves. Hopefully, they will be there at the end of closing of aforementioned PR, InshaAllah. I am really trying hard to give extra time for this app from my busiest schedule this Ramadan.

**Comment by talal** [comment]
Thanks for the fast response.

It's great to hear that this feature is already on the roadmap :)

I can understand the time constraints and how it can be difficult to maintain and add features to your open source projects.

Once again, thank you for making this app and keeping it up-to-date with new features!

**Comment by faisalcodes** [comment]
These features have been implemented in #211. Kindly test the [debug build](https://github.com/AlfaazPlus/QuranApp/suites/12247298342/artifacts/648090057) to see everything goes well.

**Comment by talal** [comment]
You link leads to 404. Can you give me a direct link to the APK?

**Comment by faisalcodes** [comment]
Its a direct link

**Comment by talal** [comment]
I still get a 404.

Perhaps the artifacts uploaded by GitHub Actions are not visible to everyone. You can access them because you are the repo owner.

Try opening your link while you're signed out of your GitHub account.

**Comment by faisalcodes** [comment]
Not true, I shared the artifact link to other people, they were able to download it.

**Comment by talal** [comment]
My bad, it was my browser 🙈

The links works and I tested the APK.

The hardware buttons work as expected, play/pause and forward/back.

However, the auto-pause on earphones disconnect doesn't work. The audio keeps playing after disconnection.

**Comment by faisalcodes** [comment]
It should work, please try again. Look at the headset icon in notification bar:

https://user-images.githubusercontent.com/62804272/232249870-fadc3665-a2a1-4e76-88a8-7cf11c81ba03.mp4

**Comment by talal** [comment]
Did you test with a bluetooth device?

I tried with two different wireless earphones and the auto-pause did not work.

Kindly see the attached screen recording, notice the bluetooth icon in the status bar and active device in the settings app. Even after disconnection the audio continues to play.

https://user-images.githubusercontent.com/3526562/232251912-e046ba25-c507-4a76-a35c-af41c0ad615c.mp4

**Comment by faisalcodes** [comment]
Okay you are talking about wireless devices. The support is currently only for wired. I will add the support for wireless as well Inshaallah.

**Comment by talal** [comment]
Thanks!

**Comment by faisalcodes** [comment]
I have added support for wireless as well. It should be noted that the player may or may not pause when you change the audio source intentionally using the following button:

![Screenshot_2023-04-16-11-42-51-47_b783bf344239542886fee7b48fa4b892](https://user-images.githubusercontent.com/62804272/232276898-ffb08b59-3cd9-4cf7-80b0-b0ccc23479c5.jpg)

**Comment by talal** [comment]
I tested the latest APK from your PR and auto-pause now works with wireless earphones 🚀
