### ISSUE TITLE
kanzul iman english 

### ISSUE THREAD

**Issue by test2a** [AlfaazPlus/QuranApp#335]
### Describe your suggested feature

Hi...

Been working for some time on https://github.com/test2a/kanzulimanenglish

so would you be interested in accepting this english translation into the app?

I see that the json is different from yours, i have kept this in a simple

```
"1.1.txt":"Allah in the name of The Most Affectionate, the Merciful.",
```
manner so if that will be okay for you, let me know and i will submit a PR.
 If you want the JSON in a particular manner,  please suggest a way i can generate this JSON from the data or redo the existing json so that it is compatible

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
I would like to know where did you take the translation from?

**Comment by test2a** [comment]
Ahadees.com scraping.

**Comment by test2a** [comment]
https://ahadees.com/english-translation.html

**Comment by faisalcodes** [comment]
Tanzil.net also has this translation. I am not planning to add Kanzul Imam in English right now.
