### ISSUE TITLE
Incorrect Author and Book Translation Information

### ISSUE THREAD

**Issue by hunnas47** [AlfaazPlus/QuranApp#336]
### Steps to reproduce

1. Go to the translation downloading section
2. Click on Language Malayalam (മലയാളം)
3. Now you can see Malayalam translator with display name "അബ്ദുൽ ഹമീദ് ഹൈദർ, കൻഹി മുഹമ്മദ്" (First translation in that language)

### Expected behavior

The display name should be "അബ്ദുൽ ഹമീദ് & പറപ്പൂർ" and authors are "ചെറിയമുണ്ടം അബ്ദുൽ ഹമീദ് മദനി, കുഞ്ഞിമുഹമ്മദ് പറപ്പൂർ"

## Expected behavior
display name = "അബ്ദുൽ ഹമീദ് & പറപ്പൂർ"
author = "ചെറിയമുണ്ടം അബ്ദുൽ ഹമീദ് മദനി, കുഞ്ഞിമുഹമ്മദ് പറപ്പൂർ"

### Actual behavior

The app currently displays incorrect information about the **Malayalam language** translators of the Quranic verses. 

## Actual behavior
display name = "അബ്ദുൽ ഹമീദ് ഹൈദർ, കൻഹി മുഹമ്മദ്"
author = "അബ്ദുൽ ഹമീദും കാനിയും"

This misinformation can mislead users so i hope you will fix this very soon.

### QuranApp version

2023.05.23.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
Thank you for reporting. Would you like to check [this](https://quranenc.com/en/home#:~:text=Translation%20of%20the%20Quran%20meanings%20into%20Malayalam%20by%20Abdul%2DHamid%20Haidar%20Al%2DMadany%20and%20Kanhi%20Muhammad) out? Kindly tell me what's your thought on it.

**Comment by hunnas47** [comment]
Thank you for your prompt attention to this issue. Unfortunately,  **both of them are incorrect.** It appears that the error stems from the inaccurate outputs of online English-to-Malayalam translators. Often, these translators produce similar but incorrect words, particularly when it involves names."

**Comment by faisalcodes** [comment]
Please attach references to support your claim. I will modify it regardless of what other sites do, if I have enough references to assess. You can provide pictures of a physical book or anything else.

**Comment by hunnas47** [comment]
Yeah here is one [link](https://tanzil.net/trans/).
More:-
-  [1](https://kanzululoom.com/pdf/quran-malayalam/)
- [Book1](https://ahlussunnabooks.org/product/%E0%B4%B5%E0%B4%BF%E0%B4%B6%E0%B5%81%E0%B4%A6%E0%B5%8D%E0%B4%A7-%E0%B4%96%E0%B5%81%E0%B5%BC%E0%B4%86%E0%B5%BB-%E0%B4%AA%E0%B4%B0%E0%B4%BF%E0%B4%AD%E0%B4%BE%E0%B4%B7-%E0%B4%9C%E0%B5%81%E0%B4%B8-2/)
- [Book2](https://www.amazon.in/Holy-Quran-Complete-Translation-Revised/dp/B092YY2VB9)
Hope this is enough.

**Comment by faisalcodes** [comment]
Thank you for the links, I will do quick research on it, tomorrow. I will let you know with the final decision. Kindly help me when needed as I don't know Malayalam.

If you would like, join our discord server (link on homepage), where some members are from Kerala.

**Comment by faisalcodes** [comment]
@hunnas47 I am considering renaming the author. Thank you for bringing this to my attention. Can you please also tell the name of the translation book. If there is none, then I put the authors' name as book name.

**Comment by hunnas47** [comment]
It does not have a specific title, is widely recognized on the internet as 'അബ്ദുൽ ഹമീദ് & പറപ്പൂർ'. So it would be better to keep that name.
