### ISSUE TITLE
Please remove internet access of app

### ISSUE THREAD

**Issue by Justauser0** [AlfaazPlus/QuranApp#345]
### Describe your suggested feature

Please remove internet access of app (offline app is more private than online ) 
and add option to import translation from storage

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
Thank you for reporting. You only need to download the resources once and you can use the app in offline mode forever after. I cannot completely disable internet access.

If you want to use it without internet access then you can, it has 3 pre-installed translations.

To be honest every phone has internet access and it's not a big deal to use the QuranApp with internet access. It doesn't collect any data, nothing leaves your phone, and the resources are downloaded from open-source sources. So you don't need to worry about it.

**Comment by Justauser0** [comment]
> Thank you for reporting. You only need to download the resources once and you can use the app in offline mode forever after. I cannot completely disable internet access.
> 
> If you want to use it without internet access then you can, it has 3 pre-installed translations.
> 
> To be honest every phone has internet access and it's not a big deal to use the QuranApp with internet access. It doesn't collect any data, nothing leaves your phone, and the resources are downloaded from open-source sources. So you don't need to worry about it.

Still even some Keyboard  app have data breach 
So how could we trust on online apps

https://www.bbc.com/news/technology-42238574

**Comment by faisalcodes** [comment]
The app is not connected all the time to the internet but only when something is to be downloaded.

> So how could we trust on online apps

Well, the source code is publicly available for a reason. You may verify yourself how it is implemented.

**Comment by faisalcodes** [comment]
A hadith app is in development, InshaAllah. You may find updates [here](https://github.com/AlfaazPlus/SunnahApp). But I am not sure if it will be completely offline. It may need to implement on-demand hadiths downloading to avoid overhead.

**Comment by Justauser0** [comment]
> A hadith app is in development, InshaAllah. You may find updates [here](https://github.com/AlfaazPlus/SunnahApp). But I am not sure if it will be completely offline. It may need to implement on-demand hadiths downloading to avoid overhead.

Please upload app on  f-droid
