### ISSUE TITLE
Show duas and dhikr in quran

### ISSUE THREAD

**Issue by ghost** [AlfaazPlus/QuranApp#347]
### Describe your suggested feature

Show duas and dhikr in quran (Said By prophets)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
Can you give me a data source to include it?

**Comment by GoRaN909** [comment]
> Can you give me a data source to include it?

I think he/she meant Hadith's by Prophet (Peace Be Upon Him)!

**Comment by faisalcodes** [comment]
@GoRaN909 In that case, it cannot be implemented as this app is solely for Quran.

**Comment by Justauser0** [comment]
> > Can you give me a data source to include it?
> 
> I think he/she meant Hadith's by Prophet (Peace Be Upon Him)!

No I meant by  all duas said by prophets in quran

Example 

https://myislam.org/dua-of-prophet-ibrahim/

https://myislam.org/rabbi-zidni-ilma/

**Comment by faisalcodes** [comment]
There is already Duas section in the app. But yes your feature can be implemented. For that someone will need to prepare a list of all duas by prophets in Quran.
