### ISSUE TITLE
Audio Player Buffering Mistakes(BUGs)!

### ISSUE THREAD

**Issue by GoRaN909** [AlfaazPlus/QuranApp#351]
### Steps to reproduce

Select an Surah then choose any Quran reciters to play the surah it will start playing from aya 1 to aya 12 then suddenly returns back to the beginning of surah or to the aya no. 2!

It happened to me while listening to surat Al-Mulk with both Qari (Saad Ghamdi & Abu Bakr As-Shatri)

### Expected behavior

Play the surah vers by vere till end!

### Actual behavior

...

### QuranApp version

2023.05.23.3

### Android version

Android 13

### Other details

No need to screenshot the title is telling everything!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
Thank you for reporting!
