### ISSUE TITLE
Search words and verses related to it  

### ISSUE THREAD

**Issue by Justauser0** [AlfaazPlus/QuranApp#355]
### Describe your suggested feature

Like this 

![IMG_20230624_175724](https://github.com/AlfaazPlus/QuranApp/assets/135147872/30446589-a1e1-4224-8de4-cb668a20881d)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
This feature is already in the app.
![Screenshot_2023-06-30-20-01-28-48_c94a05ab7f2589d5f6ad1ed708497da6.jpg](https://github.com/AlfaazPlus/QuranApp/assets/62804272/d1cb9111-d853-4b62-a644-cf72c7fe9da9)
