### ISSUE TITLE
Is there any way to see Quran tafsir offline

### ISSUE THREAD

**Issue by Justauser0** [AlfaazPlus/QuranApp#358]
### What is your question?

Is there any way to see Quran tafsir offline

### Acknowledgements

- [X] I have searched for existing issues and have **not** found an answer to my question.
- [X] I have included all necessary details in my question.
- [X] I understand that the maintainers or contributors may not be able to immediately respond to my question.

**Comment by Luciogi** [comment]
Tafseer is downloaded as you view once online

**Comment by Justauser0** [comment]
> Tafseer is downloaded as you view once online

Is there any option to download entire tafseer

**Comment by faisalcodes** [comment]
Currently entire tafsir cannot be downloaded offline.

**Comment by rezat-c** [comment]
Please add the ability to download tafsir, as it is done with translations

**Comment by rezat-c** [comment]
Please add the ability to download tafsir, as it is done with translations
