### ISSUE TITLE
Long press to copy translation or ayah

### ISSUE THREAD

**Issue by ghost** [AlfaazPlus/QuranApp#363]
### Describe your suggested feature

Is there any option to copy only translation

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
Yes there is an option. Follow these steps:
1. Click ayah menu
2. Click **Share**
3. Click **Advance Sharing**
4. Click **Share** and copy from system share dialog.

**Comment by faisalcodes** [comment]
It is not a good user experience in my opinion. It is sometimes annoying. For a mobile app it is not usual but works well for a website.

Second, I am busy in some projects right now, will come back to improve this app further InshaAllah.
