### ISSUE TITLE
Bookmark Page view not working

### ISSUE THREAD

**Issue by raiadnan** [AlfaazPlus/QuranApp#370]
### Steps to reproduce

null

### Expected behavior

null

### Actual behavior

I've tested your app. Bookmark works fine in translations view but when you selected page view style from settings and then bookmark any ayah then bookmark still showing ayah with translation instead of the page view style.

### QuranApp version

2023.07.02.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
Only the verse is bookmarked, not the layout or view. Moreover, page view style is not yet supported in a verse or verse range. So this is not an issue.
