### ISSUE TITLE
Issue when trying to share a verse again

### ISSUE THREAD

**Issue by NotSoNitro** [AlfaazPlus/QuranApp#410]
### Steps to reproduce

1. Choose a verse and select the share option for that verse
2. Share normally or with advanced sharing
3. Copy the verses or send it to the app of your choice
4. Try and share again on the same page without exiting the page

It will not let you share again, you can fix it by exiting the page and going back but then you'll have to go back to the verse you were at.

### Expected behavior

You should be able to share again like you did the first time

### Actual behavior

Doesn't work the second time at all.

### QuranApp version

2023.09.17.1

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
Thank you for reporting! I'll look into this issue.
