### ISSUE TITLE
Surahs Auto-next function not working during recitation 

### ISSUE THREAD

**Issue by kcryptonian** [AlfaazPlus/QuranApp#414]
### Steps to reproduce

1. Just open any surah 
2. Tap the play button to play the recitation audio till the end of the surah
3. Instead of the app to open the next surah and play it's audio, it just stops at the last verse of the just finished surah

### Expected behavior

The app is supposed to open the next surah and play it's audio

### Actual behavior

 it just stops reciting at the last verse of the just finished surah

P.s: I have the "autoplay next" on. I even toggle it off and on but the issue persists

### QuranApp version

2023.09.17.1

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
Thanks for reporting! This is not a bug as it is intended.

Right now, a recitation plays for the range of full chapter or full Juz only. If you want to play the next chapter or next Juz, you have to do it manually. It doesn't auto transition.

I hope to support it in the future Inshallah.
