### ISSUE TITLE
What is usesCleartextTraffic needed for?

### ISSUE THREAD

**Issue by IzzySoft** [AlfaazPlus/QuranApp#423]
### What is your question?

I just saw the app declares the `android:usesCleartextTraffic` flag – which is only needed if insecure sites (i.e. such that do not support SSL/https) must be accessed. Is this really needed – and if so, what for? If not: mind to remove that flag to enhance security?

### Acknowledgements

- [X] I have searched for existing issues and have **not** found an answer to my question.
- [X] I have included all necessary details in my question.
- [X] I understand that the maintainers or contributors may not be able to immediately respond to my question.

**Comment by faisalcodes** [comment]
In the release build it is set to `false`. I was using some local server for the development initially and I had to change it back and forth. That's why It's set `true` for debug builds only in the `app/build.gradle`.

**Comment by IzzySoft** [comment]
I'm talking about the release build here (the one attached to your releases), there's no debug flag set. So somehow `usesCleartextTraffic` made it into the release build. Check for yourself: take the APK from the latest release, and run `androiguard axml 2024.01.14.1-release.apk`. You will find

```
<application android:theme="@7F1302D1" android:label="@7F12001D" android:icon="@7F100000" android:name="com.quranapp.android.QuranApp" android:allowBackup="true" android:supportsRtl="true" android:extractNativeLibs="true" android:fullBackupContent="true" android:usesCleartextTraffic="true" android:networkSecurityConfig="@7F150002" android:roundIcon="@7F100001" android:appComponentFactory="androidx.core.app.CoreComponentFactory" android:dataExtractionRules="@7F150000">
```

which includes `android:usesCleartextTraffic="true"`. And it's declared in main (not debug) [here](https://github.com/AlfaazPlus/QuranApp/blob/master/app/src/main/AndroidManifest.xml#L26).

**Comment by faisalcodes** [comment]
Yes, you are right. But `cleartextTrafficPermitted` in [network_security_config.xml](https://github.com/AlfaazPlus/QuranApp/blob/master/app/src/main/res/xml/network_security_config.xml) is set to false for the release build. **http** requests still cannot be made.

**Comment by IzzySoft** [comment]
Then why declaring it in the Manifest and raise "false alerts"? Wouldn't it be better to remove that definition alltogether, especially if it's not needed? The updater in my repo will raise an alert for each of your versions now. And one day, that will become visible to those using my repo (once that's implemented in the web presence) and raise eyebrows – needlessly.

**Comment by faisalcodes** [comment]
It's not needed as I don't do local development for this app anymore. I'll remove it in the next version.

**Comment by IzzySoft** [comment]
Great, thanks!
