### ISSUE TITLE
Crash when starting audio

### ISSUE THREAD

**Issue by Patafix** [AlfaazPlus/QuranApp#426]
### Steps to reproduce

Click play button on a surah

### Expected behavior

Surah must be play

### Actual behavior

Crash and return to the Surah sélection page

### QuranApp version

2024.01.14

### Android version

14

### Other details

android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{4768e78 22794:com.quranapp.android/u0a488} targetSDK=34
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
	at android.app.Miss... 1075 more chars

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
Thanks for reporting!

Does it happen everytime you try to play?

**Comment by Patafix** [comment]
Yes everytime.
I try: 
 - Change recitator
 - Empty data of the app redownload audio
 - Even full reinstall of the app
Thanks for you're work on this project.

**Comment by faisalcodes** [comment]
Got it! This problem seems only on Android 14. Should be fixed soon.
