### ISSUE TITLE
Help and enhancement 

### ISSUE THREAD

**Issue by Mohammedx5** [AlfaazPlus/QuranApp#444]
### Describe your suggested feature

Can you add a arabic without translate to English and add (1)hefd counting and (2) dayle reading counting 
1-حظ 
2-ورد يومي
هل يمكنك اظافة تتبع لقراءة الورد اليومي والحفظ
على سبيل المثال اختيار الجزء أو عدد الصفحات يوميا 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by Luciogi** [comment]
> Can you add a arabic without translate to English
Does it mean, Disabling all translations?
