### ISSUE TITLE
Why is the download speed so slow?

### ISSUE THREAD

**Issue by alr86** [AlfaazPlus/QuranApp#451]
### What is your question?

It takes above 3 minutes just to download Bismillah Rahman Rahim, for example, the translations are downloaded quickly, or in the data section of ReadMe on GitHub, all the sources were playing the sound quickly, but the program is slow.

### Acknowledgements

- [X] I have searched for existing issues and have **not** found an answer to my question.
- [X] I have included all necessary details in my question.
- [X] I understand that the maintainers or contributors may not be able to immediately respond to my question.

**Comment by Luciogi** [comment]
data is fetched from quran.com
something slow there may be

**Comment by alr86** [comment]
Please add the ability to use other sources🙏
