### ISSUE TITLE
قطع في الملفات الصوتية لآيات القرآنية 

### ISSUE THREAD

**Issue by MAZEN-AD** [AlfaazPlus/QuranApp#452]
### Describe the issue

لاحظة وجود قطع في اخر الملفات الصوتية الخاصة بالآيات عند تشغيل القراءة الصوتية للسورة القرآنية، حيث القطع ينقص من كلمات الآية في بعض السور.
لاحظة ذلك في صوت الشيخ ياسر الدوسري و ناصر القطامي
تحديدا في السور القصيرة في جزء عم.
لاحظة أيضا وجود تداخل في الآية بما بعدها.

### Screenshot

![Screenshot_2024-03-16-15-01-39-451_com quranapp android-edit](https://github.com/AlfaazPlus/QuranApp/assets/136689959/a1aa7a31-dfcd-4e03-8815-9194e4753960)

### Chapter and verse numbers

Verse 1 and 2 

### QuranApp version

2024.02.04.1

**Comment by Luciogi** [comment]
what he say?
