### ISSUE TITLE
Download entire recitation of the recitor

### ISSUE THREAD

**Issue by Gamer750** [AlfaazPlus/QuranApp#456]
### Describe your suggested feature

Download entire recitation of the recitor like we download the translation I know how much space will it take 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
You can pre-download all the recitations from the settings.

Menu > Settings > Manage Audio

**Comment by Gamer750** [comment]
Do we have any option to download completely instead of clickjng one by one

**Comment by Gamer750** [comment]
> You can pre-download all the recitations from the settings.
> 
> Menu > Settings > Manage Audio

Bro could you add abdallah humeid and salman utahbi recitation they are good qari

**Comment by faisalcodes** [comment]
> Do we have any option to download completely instead of clickjng one by one
Currently no, you can download multiple verses simultaneously

> Bro could you add abdallah humeid and salman utahbi recitation they are good qari
If it's available on quran.com then it can be added.

**Comment by Gamer750** [comment]
Unfortunately I can't find their recitation.
