### ISSUE TITLE
Add a new Malayalam translation

### ISSUE THREAD

**Issue by Gamer750** [AlfaazPlus/QuranApp#472]
### Describe your suggested feature

By Prof. V. Mohammed. It has mostly accurate translation

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
Currently, only translations available on quran.com can be added.

**Comment by Gamer750** [comment]
Then add translation in Quran.com
