### ISSUE TITLE
App on Fdroid and Izzyondroid 

### ISSUE THREAD

**Issue by ARBoyGo** [AlfaazPlus/QuranApp#7]
### Describe your suggested feature

Publish this app on Fdroid and Izzyondroid, We need more devs to contribute, More people are using it. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
@IzzySoft May I know the status of QuranApp packaging on F-droid? How much time does it takes to be packaged? I saw [this](https://f-droid.org/en/docs/Inclusion_How-To/#:~:text=it%E2%80%99s%20mostly%20just%20a%20matter%20of%20time%20before%20F%2DDroid%E2%80%99s%20official%20build%20server%20will%20fetch%2C%20build%2C%20and%20publish%20your%20application%20on%20the%20main%20F%2DDroid%20repository).

**Comment by IzzySoft** [comment]
I guess we're waiting for a release with fastlane in. But I can trigger a rescan to see if it's already picked up now, though I doubt that; IIRC the bot always looks at the latest tag. Do you plan another release soon?

**Comment by faisalcodes** [comment]
Yes, but the next release may take about 1 week after the [milestone](https://github.com/AlfaazPlus/QuranApp/milestones) is reached. We can wait though. I will remind you after the next release 😊

**Comment by IzzySoft** [comment]
Thanks! I see the bot picked up fastlane, so all seems ready. But as a MR usually takes a week or more (depending on who has time when and decides to pick up), it makes sense to start with the next release to have all set properly. Looking forward to your ping then – ideally in the RFP so I don't have to search it then. [Linking it here](https://gitlab.com/fdroid/rfp/-/issues/2387) for convenience :wink:

**Comment by iamtalhaasghar** [comment]
Update: The app is now available on Izzy on Droid repo.

Special thanks to @IzzySoft and @faisalcodes.

Lots of ❤ from 🇵🇰

**Comment by faisalcodes** [comment]
@iamtalhaasghar The app has been available on IzzyOnDroid for over 20days now. But I am waiting for it to be packaged in F-droid.

**Comment by faisalcodes** [comment]
@IzzySoft It's been over a week now since the app was ready. Are there more requirements that should be met? I have seen RFP's for several apps, which was after this one's, have already been processed. I wonder if there is something I need to do.

**Comment by IzzySoft** [comment]
@faisalcodes https://monitor.f-droid.org/builds/running (the build queue is stuck since 5 days, nothing I can do about it, sorry)

**Comment by faisalcodes** [comment]
There has been several builds since the issue was fixed but I see no progress on my RFP.

**Comment by faisalcodes** [comment]
@IzzySoft Hi how are you.

I wanted to know if you keep track of number of downloads from your repository. Some people reported to me that they came from F-Droid (IzzyOnDroid).

**Comment by IzzySoft** [comment]
No, I don't, sorry.

**Comment by faisalcodes** [comment]
Looks like we cannot get it published on F-droid. In that case, Google Play Store, GitHub and IzzyOnDroid should be enough.

**Comment by faisalcodes** [comment]
There have been some compatibility issues there. It was tried to solve several times but with no success.
