### ISSUE TITLE
Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [AlfaazPlus/QuranApp#73]
### Describe your suggested feature

Hi, thanks for creating this app.
Please add support the Android 13 "Themed Icons" feature.

![Screenshot_2023-03-02-00-15-53-982_de mm20 launcher2 release](https://user-images.githubusercontent.com/23485114/222261503-4db502d5-aeae-4a9a-a3d3-3063f345f7c6.jpg)

It's not my theme or my icon pack, it's a feature from Android 13.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
Will start working on it, InshaAllah.

**Comment by xmha97** [comment]
Thanks 🙏

**Comment by faisalcodes** [comment]
Now can you check it out if it works?
