### ISSUE TITLE
Persian (Farsi) translation

### ISSUE THREAD

**Issue by xmha97** [AlfaazPlus/QuranApp#74]
### Describe your suggested feature

Please add the Persian (Farsi) translation.
Thanks 🙏

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
It may take time to add a new translation. I will start working on it shortly, InshaAllah.

**Comment by xmha97** [comment]
Thanks 🙏

**Comment by faisalcodes** [comment]
Currently font for the Persian translation is the default one. In the next release Persian font will be same as of Urdu.

**Comment by xmha97** [comment]
You can use this font:
https://github.com/rastikerdar/vazirmatn
