### ISSUE TITLE
Don't stop the Quran recitation when the Quran Reader exits.

### ISSUE THREAD

**Issue by xmha97** [AlfaazPlus/QuranApp#75]
### Steps to reproduce

1. Go to the app
2. Open the reader
2. Play the Quran recitation
3. Exit the reader
4. Quran recitation stopped!

### Expected behavior

Don't stop the Quran recitation.

### Actual behavior

Stopped the Quran recitation.

### QuranApp version

2023.03.01.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
The Quran recitation will only play as long as Quran reader is opened. When you close the Quran reader the player will stop. It is not an issue as the behavior is as expected. Your issue can be labeled as a feature request.

**Comment by faisalcodes** [comment]
After thinking a lot, I have come to a conclusion that this is not useful for the scenario of the QuranApp. The recitations should be played only if the reader is open.
