### ISSUE TITLE
Clarify the non free dependancies 

### ISSUE THREAD

**Issue by not-programmer98** [AlfaazPlus/QuranApp#86]
### Describe your suggested feature

I hope Clarify the non free dependancies that used by the app especially on the fdroid description since the community care about this and may stop some from downloading the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
QuranApp does not depend on any non-free software. If you think it does, then kindly point it out and I will put it in the documentation. Anyway this app is not uploaded on F-droid (yet).

**Comment by ARBoyGo** [comment]
@izzysoft 
QuranApp is not depending on non-free dependancies
Can you check, And tell why is it showing in your repo?

**Comment by IzzySoft** [comment]
@ARBoyGo you can always check with the "libraries" section on the APK when visiting the app with a browser. Offending libs have a marker. In your case:

![image](https://user-images.githubusercontent.com/6781438/224484012-882da077-b5f2-4706-a40c-58c4c2bad06f.png)

That framework is proprietary (not open-source). The term "free" is to be understood as "libre" – so proprietary is not "libre".

**Comment by faisalcodes** [comment]
It is because of the `oss licenses` library.

@IzzySoft Will removing it automatically update your repository?

**Comment by ARBoyGo** [comment]
@IzzySoft, BTW, I don't know how this app get on your repo, The developer seems didn't request you to add it. Anyway thanks for adding it.

**Comment by IzzySoft** [comment]
> It is because of the `com.google.android.gms.play-services-oss-licenses` library.

Yupp, that name is quite misleading, isn't it? Having proprietary dependencies, it only *lists* open-source libraries. One could think the name was intentionally kept ambiguous (to lure in foss devs). [See here](https://gitlab.com/-/snippets/1896503#license-dialogs) for some alternatives.

> Will removing it automatically update your repository?

Semi-automatically. My updater should report to me about a most-likely obsolete anti-feature – which then causes me to verify and act accordingly, usually within a day. So it should be removed with a day's delay then.

> Thanks for having it there, really appreciated.

Gladly! If you look around in my repo, you will find several more apps around Qur'an, Sala, Qibla, Adhan, Dhikr… And I also added your app to my collection of [apps for Muslims](https://android.izzysoft.de/applists/category/named/religion_islam). Enjoy :smiley:

**Comment by faisalcodes** [comment]
> Semi-automatically. My updater should report to me about a most-likely obsolete anti-feature – which then causes me to verify and act accordingly, usually within a day. So it should be removed with a day's delay then.

I will replace or remove it.

> And I also added your app to my collection of apps for Muslims.

Thank you, I really appreciate it. Keep doing what you are doing, I endorse it.

**Comment by ARBoyGo** [comment]
@IzzySoft May God bless you brother for you work.

**Comment by IzzySoft** [comment]
Thanks! As it's said: "Help one another in acts of piety and righteousness." (5:2) Trying my best :smiley:

Oh, btw: I see 2 badges in the Readme, one for Play and one for github. 3 is an important number – so if you wish you can [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to accompany the two, pointing to the new presence in my repo :wink:

**Comment by IzzySoft** [comment]
Thanks for adding the badge! And congrats to your RFP, looks good so far. I've just opened a PR to add the needed Fastlane structures – so once they are in place we'll have issuebot perform another scan (to confirm all is fine), and then can proceed to a merge request adding the app's metadata to the F-Droid repository. Again, 3 is a good number, we'll meet there as well I guess (disclosure, if I didn't do that yet: I'm one of the maintainers over there, too).

**Comment by faisalcodes** [comment]
I can see you are everywhere 😀.

**Comment by IzzySoft** [comment]
> you are everywhere

Well, not quite. You won't find me on PlayStore, TikTok, WA, Facebook, Insta… Just in the "free world" I'm indeed in many places :smile:

**Comment by ARBoyGo** [comment]
@IzzySoft How do you find this repo? Like I was using Droid Ify suddenly I saw you QuranApp on your repo. 
I asked Faisal he said He didn't request, Well, I wrote an issue to publish on your repo and Fdroid, 

Anyway thanks, I'm impressed by your work ☺️

Ex - Privacy Enthusiast lol 😂 I can't live without Instagram and WhatsApp. Rest I don't use. Maybe rarely messenger 💀😭 to get my old friends who only use it.

**Comment by IzzySoft** [comment]
> How do you find this repo?

I have my agents. They report back to me. If they bring in something interesting (i.e. an app matching the inclusion criteria of my repo but not yet present there or at F-Droid), I take it in.

> I wrote an issue to publish on your repo and Fdroid,

Already working on it :smiley:

> I can't live without Instagram and WhatsApp.

Aw, easily. No MS here, no FB/Meta either. If I'd want something like Insta, I'd take a look at Pixelfed. Instead of WA, there are lot of alternatives (one you already discovered: Matrix, though I'm not in there either – one cannot really be everywhere). And yes, strong privacy proponent :wink:

**Comment by faisalcodes** [comment]
@IzzySoft Can you force update your repo so that it does not show "non-free dep" warning? The non-free dep has already been removed.

**Comment by IzzySoft** [comment]
Is it that urgent that it cannot wait for the regular update? You've just missed today's by about an hour unfortunately.

**Comment by faisalcodes** [comment]
If that is so, can wait.

**Comment by IzzySoft** [comment]
Updater runs once every 24h. If the scanner detects an anti-feature no longer "covered", it alerts me (with few exceptions like NonFreeNet which cannot be told just by libraries). I then usually act ASAP correcting that, so with the sync right after that it shows fixed. In your case, I'll trigger another sync then manually right after removing the AF so you won't have to wait another 24h.

**Comment by IzzySoft** [comment]
Just updated and triggered the sync, it completed right now. Thanks for the note: NonFreeDep is one of the AFs which do not cause a notice when the underlying lib is gone (as it's not always bound to a lib). Website should reflect it in a minute or so.

**Comment by faisalcodes** [comment]
Thanks a lot. Now I can close this one.

**Comment by IzzySoft** [comment]
Thanks for taking care!
