### ISSUE TITLE
Add the ability to play a specific verse by clicking in Page-view layout.

### ISSUE THREAD

**Issue by not-programmer98** [AlfaazPlus/QuranApp#87]
### Describe your suggested feature

The only way now to play is be starting from the beginning of سورة which is not convenient, it would be great if you add the ability to play a specific verse.
And thank you for the great app.
ربنا يجزيكم خير

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
This feature is already there. You can play any verse by clicking the play button  given on every verse. Kindly use the app thoroughly to know about its features.

**Comment by faisalcodes** [comment]
Thank you for your prayers. ❤️

**Comment by not-programmer98** [comment]
No, I'm not talking about the translation view I'm talking about the page view. I can't do this in page view.

**Comment by faisalcodes** [comment]
The page view layout is intended only for reading. It should be free of distractions and should not contain extra controls. That's why translation view layout is there.

**Comment by not-programmer98** [comment]
But translation view layout is more likely for learning and it's good for that, but right now I have to use a closed source app for that purpose that I want you add.
I think it will be great, let's make it reading and listening mode, also there's a good app for just reading called nour-alhuda but I have to used a closed source app with adds for listening.

**Comment by faisalcodes** [comment]
I will work on it. I hope it to be implemented in the next release InshaAllah.

**Comment by not-programmer98** [comment]
Thank you
ربنا يجزيكم خير
