### ISSUE TITLE
Translation Add Request

### ISSUE THREAD

**Issue by saifalisew1508** [AlfaazPlus/QuranApp#91]
### Describe your suggested feature

please add hindi translation of quran in this app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment]
There is already a hindi translation in the app. Follow these steps:

1. Go to settings
2. Click `Select translation`
3. On the top right corner click download icon
4. Select the hindi translation

**Comment by saifalisew1508** [comment]
thanks for this awesome app
